# Generated by Django 4.2.7 on 2023-11-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='дата платежа')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='Сумма платежа')),
                ('payment_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='валюта платежа')),
                ('payment_api_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='id платежа на платежном сервисе')),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='ссылка на возврат')),
                ('state', models.BooleanField(default=False, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='product_stripe_id')),
                ('price_stripe_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='price_stripe_id')),
                ('price', models.PositiveIntegerField(default=49, verbose_name='"цена"')),
                ('currency', models.CharField(blank=True, choices=[('rub', '₽'), ('usd', '$'), ('eur', '€')], default='rub', max_length=3, null=True, verbose_name='валюта')),
                ('content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='content.content', verbose_name='Продукт')),
            ],
        ),
    ]
