# Generated by Django 4.2.7 on 2023-11-24 11:53

from django.db import migrations, models
import django.db.models.deletion
import users.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(default=None, upload_to=users.services.user_directory_path_content, verbose_name='изображение')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='дата последнего обновления')),
                ('start_publish', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время публикации')),
                ('is_publish', models.BooleanField(default=False, verbose_name='публичный доступ')),
                ('is_free', models.BooleanField(default=True, verbose_name='Бесплатный контент')),
                ('is_paid_subs', models.BooleanField(default=False, verbose_name='Контент в подписке на пользователя')),
                ('is_src_subs', models.BooleanField(default=False, verbose_name='Контент в подписке на сервис')),
                ('is_purchase', models.BooleanField(default=False, verbose_name='Доступно для приобретения в коллекцию')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='ссылка на видео')),
                ('video_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='ID видео')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='content.content', verbose_name='контент')),
            ],
        ),
    ]
